clnsmth/soso

environment-min.yml, environment.yml, poetry.lock, pyproject.toml, requirements.txt, src/soso/utilities.py, tests/test_utilities.py
Read a SSSOM file of a specified metadata standard into a dataframe so the flow control logic of the convert function may access the match semantics (predicate) when deciding if a SOSO property meets an accuracy threshold specified by the user. For example, the convert function could have a parameter allowing the user to set a match threshold below which SOSO properties are not created and included in the final SOSO record.
This allows users to control the accuracy of derived SOSO records to meet the requirements of specific use cases.
=> feat: read SSSOM for flow control logic

src/soso/utilities.py
Replace deprecated methods with preferred ones to silence warnings issued by pytest. Fix inaccurate return type descriptions in associated functions.
=> fix: deprecation warnings issued from pytest

poetry.lock, pyproject.toml, src/soso/interface.py, src/soso/main.py, src/soso/strategies/eml.py, src/soso/utilities.py, tests/conftest.py, tests/test_interface.py, tests/test_main.py, tests/test_strategies.py, tests/test_utilities.py
Read a metadata file into an object and store it in a "metadata" class attribute for strategy methods to access when converting to SOSO properties. Define metadata file reader types on a strategy-by-strategy basis to accommodate different file formats across metadata standards.
Wrap similar path finding functions in a common interface to simplify the code base. Access each path finding function by an identifier for each metadata standard.
=> feat: read metadata for strategy method access

src/soso/utilities.py, tests/test_utilities.py
Use the name "strategy" instead of "standard" for parameters that control the conversion methods to be used on a metadata file. Do this for the sake of consistency.
=> refactor: use "strategy" instead of "standard"

docs/source/dev/contributing.rst, pyproject.toml
Simplify pylint calls by declaring arguments in the pyproject.toml file rather than passing them manually with each pylint call.
=> ci: simplify pylint calls with pyproject.toml

pyproject.toml, src/soso/utilities.py, tests/conftest.py, tests/test_utilities.py
Re-enable a couple pylint checks to improve code readability, reduce accidental introduction of errors, and simplify future debugging.
=> refactor: re-enable pylint checks to improve code

src/soso/interface.py, src/soso/main.py, src/soso/strategies/eml.py, tests/conftest.py, tests/test_conftest.py, tests/test_strategies.py
Get the SOSO "url" property for the EML strategy from a user supplied argument, because there is no mapping of this property to the EML schema, and therefore no way to derive this information from an EML metadata file.
Use the flexible kwargs parameter as a solution to other unmappable properties, for the EML strategy and other metadata strategies as well. Alert users to unmappable properties and their expected value types, so they may be supplied correctly.
Create a function to test that get_url returns a URL formatted string.
=> feat: get url property from argument (#5)

src/soso/interface.py, src/soso/main.py, src/soso/strategies/eml.py, tests/conftest.py, tests/test_interface.py, tests/test_strategies.py
Add clarifying docstrings to the public-facing API to improve usage comprehension.
Reorganize method tests to define kwargs within the tests themselves instead of globally during strategy instantiation in conftest.py, preserving focused test scope.
=> refactor: enhance clarity of the public-facing API

pyproject.toml
Ignore pylint 'c-extension-no-member' (I1101) messages, originating from lxml, for sake of a readable message log.
Another option, adding lxml to the pylint --extension-pkg-allow-list, may run arbitrary code and is a decision I shouldn't make for collaborators running pylint in the context of this project.
=> ci: ignore pylint c-extension-no-member messages

src/soso/interface.py
Add the missing return type to the get_contributor method docstring. This should have been apart of
a42bd1121c92899d279adcfd630e0af00ba66e15
=> fix: add missing return type to method docstring (#5)

src/soso/strategies/eml.py
Update the behavior to return 'None' for empty 'creator' and 'contributor' properties, enhancing readability.
To maintain the order of 'creator' and 'contributor' properties, they are now enclosed in an '@list' wrapper. When 'creator' or 'contributor' is empty, an empty '@list' wrapper is returned to the graph. The use of 'None' facilitates the efficient removal of empty values from the graph as a final step in 'main.convert' before it is returned to the user.
=> fix: return None creator/contributor for readability

src/soso/strategies/eml.py
Note that the 'provider' property is unmappable and can only be added via kwargs. This should have been apart of
ed2911ff1459c50451977ccaf7919ffd33531a33
=> fix: note provider is unmappable (#5)

src/soso/strategies/eml.py
Note that the 'publisher' property is unmappable and can only be added via kwargs. This should have been apart of
f5f8f826817f98174813a53c1b9fa67a97275abb
=> fix: note publisher is unmappable (#5)

src/soso/utilities.py, tests/test_utilities.py
Rename 'get_soso_common' to improve understanding and align with the naming convention used for other methods that retrieve file paths.
=> refactor: rename method for readability

tests/test_strategies.py
Resolve the pylint warning regarding an excessively long line to maintain a clean message log.
=> fix: resolve pylint warning regarding long line

.github/workflows/ci-cd.yml
Use 'black' version 23.7.0 to match the version currently specified in the environment.yml and requirements.txt files and to prevent CI failures.
=> ci: use 'black' version 23.7.0

docs/source/dev/contributing.rst
Correct local testing instructions in the Contributor's Guide to prevent confusion caused by errors thrown during command execution.
=> docs: fix local test instructions

docs/source/dev/maintaining.rst
Correct broken references to the Angular commit style guidelines listed in the Maintainer section of the package documentation. The original resources had moved.
=> docs: fix broken reference URLs in Maintainer Guide

src/soso/interface.py
Enhance descriptions of expected return types in the strategy implementation docstrings due to the flexibility of Schema.org properties. For instance, the 'get_keywords' method may return a list of Python strings or dictionaries depending on whether the input is a simple list of keywords or a list of defined terms. Additionally, return types can be 'any' due to potential overrides by the 'kwargs' argument of strategy methods.
Clarify the usage of 'None' return types. Notify users of the strategy API that 'None' is expected from 'get' methods when a NULL result is generated. This ensures a consistent NULL return type from methods where different return types are possible, simplifying type testing for "useful values" by client code like main.convert. Note, it's the responsibility of 'get' …
=> docs: improve strategy return type descriptions

tests/conftest.py
Ignore the Pylint warning about 'too many branches' (R0912) in the case of tests.conftest.is_property_type, as the benefits of refactoring are ambiguous.
=> ci: ignore pylint R0912 for is_property_type

tests/conftest.py, tests/test_conftest.py, tests/test_strategies.py
Ensure that strategy methods return a None value instead of an null (empty) value or container. None values are interpreted in the final graph cleaning step of main.convert as properties with no meaningful information, which should be removed from the resulting SOSO graph before being returned to the user.
=> test: strategy methods return None, not null values

tests/conftest.py
Adjust variable names in tests.conftest.is_property_type to align with patterns used in the codebase for consistency.
=> refactor: use consistent variable names for readability

src/soso/strategies/eml.py
Implement the rm_null_values function to remove null values from the results of strategy methods before returning them to the client. This approach is recommended for strategy methods rather than main.convert to enable the direct usage of strategy methods and their results. For instance, this facilitates updating specific graph properties when a new algorithm is implemented without needing to recreate the entire dataset graph.
=> feat: apply rm_null_values to strategy methods

src/soso/utilities.py
Add a definition of what constitutes a "null" value in the rm_null_values function documentation. This clarification ensures that users can easily understand the concept without needing to inspect the code.
=> docs: define "null" in rm_null_values function

tests/test_strategies.py
Remove a duplicate word from the test name to enhance cleanliness and readability.
=> refactor: fix typo

tests/test_conftest.py
The test_is_not_null_for_non_dictionaries function does not cover null cases. Added tests to ensure comprehensive coverage of null cases for the is_not_null function.
=> test: add missing negative cases for is_not_null

tests/test_strategies.py
Implement measures to reduce false positive test results in the strategy interface by explicitly declaring which tests should be skipped, along with associated rationales. This approach avoids relying on implicit assumptions represented by a None value.
Originally, a None value was assumed to indicate that a strategy did not have a method for the property being tested. However, it became apparent that None could arise in other cases:
1. Method Not Yet Implemented: Used when a strategy method has not been implemented yet but is planned to be. This tag is applied during active development of a strategy and should be removed incrementally as methods are implemented.
2. Property Not in Schema: Applied when the source metadata dialect does not include content within the schema for the target …
=> test: reduce false positive test results

tests/test_strategies.py
Update the rationale for skipping the citation property test in the EML strategy to accurately reflect the underlying reason for its exclusion.
=> test: update rationale for skipped test

src/soso/main.py, src/soso/strategies/eml.py, src/soso/utilities.py, tests/test_utilities.py
Replace the "rm" and "clean" prefixes with "delete" in recently implemented functions to better reflect the functions' actions and to promote consistent readability and understanding.
=> refactor: apply consistent name prefixes for clarity

src/soso/strategies/eml.py
Add a note about the unmappable property for specifying coordinate reference systems (CRS) to the spatialCoverage property. This addition alerts users to the ability to customize.
=> docs: note unmappable property for CRS

tests/test_main.py
Remove a misplaced file writing block from one of the tests to prevent writing a file when the test is executed. This code block was accidentally committed in: 88e956febf0f8d55bdd019af50df9cac14219b02
=> test: fix typo in test code

docs/source/index.rst
Correct the method name reference in the opening example of the package documentation to ensure accuracy.
=> docs: fix typo in opening example

docs/source/index.rst
Temporarily remove the features section from the documentation until there are enough features to warrant a list.
=> docs: remove short list of features

docs/source/user/quickstart.rst
Include a basic usage example in the quickstart guide to help users get started quickly with the package.
=> docs: add basic usage to the quickstart guide

docs/source/index.rst, docs/source/user/quickstart.rst, src/soso/main.py
Ensure consistent representation of metadata standard acronyms in public-facing documentation in their canonical form, but process acronyms in lowercase for consistent results. This presents information to users in a familiar way, but accommodates some variation of user inputs.
=> fix: consistent representation of metadata acronyms

tests/conftest.py
Provide an explanation of the internal logic used in the 'is_property_type' test function. Do this to improve understanding and facilitate its usage.
=> docs: explain logic of is_property_type function

docs/source/dev/maintaining.rst
Emphasize the responsibility and significance for maintainers to stay informed about Science-On-Schema.Org conventions. This includes the duty to notify our developer community about any changes that may impact existing implementations.
=> docs: stay up-to-date with Science-On-Schema.Org

docs/source/dev/design.rst
Outline the method for users to define unmappable properties using parameter inputs. This documentation sets the groundwork for future implementation.
=> docs: create unmappable properties with params

docs/source/dev/design.rst
Edit the customization via parameter input section in the design documents, removing irrelevant details related to basic Python programming and an upcoming refactor. Do this for enhanced readability.
=> docs: streamline customization via parameters

src/soso/strategies/eml.py
Add explanatory notes on the two methods for including unmappable properties in the EML strategy. This sets the groundwork for an upcoming refactor.
Related to:
634bca84020ca74d264a73e3b723f8cf815ed67a
=> docs: add unmappable EML properties via parameters

docs/source/dev/design.rst
Remove a redundant statement from the design documents. This originated at: 9f25733a0b0b7c1a22a189698ef5a4a9b6aa5020.
=> docs: eliminate redundant statement

docs/source/dev/design.rst
Enhance the general customization section by adding a note that unmappable properties can be supplied through strategy-specific parameters, expanding the options beyond just `kwargs` and method overrides.
Related to: 634bca84020ca74d264a73e3b723f8cf815ed67a
=> docs: note mapping via params

tests/conftest.py, tests/test_conftest.py, tests/test_main.py
Create a utility test function (`get_kwargs`) to help instantiate strategies with parameters. Add this to the strategy instance to enable both unit and integration tests. This simulates use of parameters by clients to create otherwise unmappable properties.
=> test: instantiate strategy with parameters

src/soso/strategies/eml.py
Clarify property definitions by referencing their Schema.org formats.
=> docs: disambiguate property definitions

pyproject.toml
Ignore Pylint's `Too many arguments (R0913)` warning to simplify the creation of unmappable properties via class parameters.
=> ci: ignore Pylint 'too many arguments'

pyproject.toml
Ignore Pylint's too-many-instance-attributes (R0902) warning to simplify the creation of unmappable properties via class parameters.
=> ci: ignore Pylint too-many-instance-attributes

src/soso/interface.py, src/soso/main.py, src/soso/strategies/eml.py, src/soso/utilities.py, tests/conftest.py
Integrate type hints to support static code analysis. Apply to all APIs, not just the public-facing API. Utilize union types for functions with variable inputs/outputs when the list is not too long; otherwise, use Any. Remove type definitions in docstrings to maintain DRY (Don't Repeat Yourself) principles.
=> refactor: use type hints for static code analysis

docs/source/dev/design.rst, src/soso/strategies/eml.py
Add type hints to strategies to enable type checking and provide more informative descriptions of return types. This was overlooked in: ec9eab8b54561d3f16b0ec69d0cba9b552e32e97.
Relatedly, remove the note about intentionally vague return types from the strategy interface listed in the design documentation. We are no longer being vague.
=> refactor: add missing type hints to strategies

src/soso/strategies/eml.py, tests/test_eml.py
Raise informative exceptions for file parsing failures by the EML strategy. Currently, non-XML files input to the EML strategy result in cryptic messages raised by `lxml.etree.parse`. Wrap this operation in exception management clauses that check for the expected file type, estimated by the file extension.
Note we may want to go a step further and verify that the file is EML.
=> refactor: exception handling for EML file types

src/soso/data/eml_empty.xml, src/soso/utilities.py, tests/conftest.py, tests/test_utilities.py
Create an empty metadata file for each strategy to test the negative cases, i.e. where expected metadata content is missing. Currently, only the positive cases are tested, where the test metadata file contains all the elements mappable from the metadata standard to SOSO.
=> test: use empty metadata for testing negative cases

docs/source/dev/design.rst
Document the approach to testing both the positive and negative cases of strategy methods in the design docs. This ensures developers and maintainers of strategies understand how these cases are handled.
=> docs: note how to test positive and negative cases

src/soso/strategies/eml.py
Remove `additionalProperty`, nested within `schema:spatialCoverage`, from the list of unmappable properties for the EML strategy. We have defined unmappable properties as top-level properties that cannot be meaningfully mapped to the target metadata standard. In this case, the nested property doesn't meet this criteria.
The initial rationale behind allowing users to define nested properties as arguments to the `main.convert` method was to simplify this process. After some experience, it became evident that many nested properties meet this criteria within the EML metadata standard. Scaling this out to other metadata standards would create an overly complicated code base and likely more confusion than it's worth.
=> fix: don't list nested properties as "unmappable"

src/soso/interface.py, src/soso/strategies/eml.py, tests/test_interface.py
Make the 'file' argument, passed to the strategy class, accessible to strategy methods by adding it to the list of class attributes. The file path may contain useful metadata.
=> feat: make 'file' argument accessible to strategy methods

docs/source/_templates/sidebarintro.html, docs/source/index.rst, docs/source/user/advanced.rst
Remove the advanced section from the user documentation since there are no advanced use cases at this time.
=> docs: remove unused advanced section

docs/source/dev/design.rst
Transfer the remaining items in the System Details section of the Project Design document to established sections of the project documentation to streamline the documentation.
=> docs: refactor remaining system details of design docs

docs/source/_templates/sidebarintro.html, docs/source/index.rst
Move design docs from the contributor guide to their own section since design concepts are largely independent of contribution guidelines.
=> docs: design docs don't belong in contributor guide

docs/source/dev/design.rst
Remove the system architecture section heading, since the design document in and of itself implies system architecture. Additionally, some items listed in this section are not part of the architecture per se.
=> docs: remove architecture heading from design docs

tests/conftest.py
Update the type hints for `conftest.strategy_instance` and `conftest.strategy_instance_no_meta` to more accurately describe the return type.
=> fix: strategy_instance returns class, not PosixPath

src/soso/utilities.py, tests/test_utilities.py
Remove unused SSSOM functions from the code base. The original intent of these functions was to be part of a system that could enable users to control the accuracy of property method return values based on the mapping predicate stated in the SSSOM file. This is no longer within the project scope.
=> refactor: remove unused SSSOM functions

docs/source/dev/contributing.rst, docs/source/dev/maintaining.rst
Use Poetry consistently in the documentation for contributor/developer workflows. A few spots in the documentation demonstrate command line calls using Conda. To align with conventions, these should reference Poetry.
=> docs: use Poetry in dev workflow

docs/source/_templates/sidebarlogo.html
Synchronize the "Useful Links'' section of sidebarlogo.html to match that of sidebarintro.html. sidebarlogo.html should have been updated with recent changes to sidebarintro.html.
=> docs: sync sidebar html docs

docs/source/index.rst
Relocate the Code of Conduct from the high-level listing alongside other documents like Contributing. This is an important document, and is already referenced from relevant sections of the user documentation.
=> docs: relocate code of conduct

docs/source/dev/contributing.rst
Remove mention of Numpy docstring formatting. The adopted convention is to use reStructuredText (reST) instead. See commit: f97122705c411ed43068aab517706dff7cdf2cbc.
=> docs: remove mention of Numpy docstrings

docs/source/user/quickstart.rst
De-emphasize section headings of the Quickstart Notes so they are not visible in the table of contents alongside other items that are significantly more important.
=> docs: de-emphasize section headings of quickstart notes

docs/source/dev/design.rst
Remove references to "precision-based property control" as it is not yet implemented.
Originally, the plan was to allow users to control the precision of results from `main.convert` through a "match type threshold" parameter, which would reference the SSSOM to determine if a property mapping met the criteria to be included in the returned graph.
=> docs: remove "precision-based property control"

docs/source/dev/design.rst
Document the expected usage of the `utilities.delete_null_values` function in strategy methods. This function helps remove null values from the final graph returned by main.convert.
=> docs: new strategy methods should use delete_null_values

docs/source/dev/design.rst, src/soso/strategies/eml.py
Update the terminology used when referring to how one metadata standard (source) maps to SOSO (target) to ensure consistency.
=> docs: establish consistent mapping terminology

src/soso/strategies/eml.py, tests/test_eml.py
Avoid the `unsupported operand type(s) for +=: 'NoneType' and 'str'` exception raised when `get_content_size` appends a unit string to a size value of NoneType.
=> fix: get_content_size errors when unit not present

src/soso/strategies/eml.py, tests/test_eml.py
Fix the `argument of type 'NoneType' is not iterable` exception raised when `get_checksum` returns `None` from the EML authentication element and attempts to perform string matching on it.
=> fix: get_checksum errors on no checksum value

src/soso/strategies/eml.py
Fix the XML parsing in the get_description method to return complete values, including content contained in sub-elements.
=> fix: get_description returns incomplete value

docs/source/user/quickstart.rst
Provide instructions for installing the package from GitHub, demonstrating installation for both main and development branches.
=> docs: install from GitHub

docs/source/dev/design.rst
Fix the statement in the SSSOM file that suggests mapping predicates can be coerced to exact matches if, in the conversion code of a property, the values can be coerced to form exact matches. Ensure the SSSOM file accurately represents the level of matching between metadata standards properties and SOSO.
=> docs: don't coerce SSSOM mapping predicates

src/soso/strategies/eml.py, src/soso/utilities.py, tests/test_utilities.py
Limit textual property descriptions to 5000 characters as per Google's Dataset Structured Data Guidelines. Create a utility function to use across conversion strategies.
=> fix: limit textual property descriptions to 5000 characters

src/soso/strategies/eml.py, tests/test_eml.py
Avoid returning the OWL time `Instant` if the `numericPosition` or `timeScaleAgeUncertainty` are strings instead of the expected `xsd:decimal` type, as doing so is inaccurate.
=> fix: geo time `xsd:decimal` could be string

environment-min.yml, environment.yml
Change the conda environment name in environment.yml and environment-min.yml to match the package name for consistency. Install soso from its only distribution on GitHub.
=> build: clean up env build files

src/soso/strategies/eml.py
Use the elem is None test to address the future deprecation warning issued by Pytest.
=> fix: future deprecation warning

docs/source/dev/design.rst, src/soso/interface.py, src/soso/strategies/eml.py, tests/test_eml.py, tests/test_interface.py, tests/test_strategies.py
Enable processing of multiple versions of a metadata standard based on information contained in a metadata record. This accommodates version-specific properties that require custom processing.
Update the documentation with details about this new feature.
=> feat: convert multiple versions of source metadata

docs/source/dev/contributing.rst, docs/source/dev/design.rst, docs/source/dev/maintaining.rst, docs/source/user/quickstart.rst
Review existing documentation and edit to enhance readability, clarity, and consistency.
=> docs: review and edit documentation

.github/workflows/ci-cd.yml, pyproject.toml
- Update the failing release workflow (GitHub Action) so Python Semantic Release can automatically cut a new release when the development branch is merged into `main`.
- Add the `GITHUB_TOKEN` to the semantic release step, where it is needed for committing changes, using the standard syntax for referencing secrets.
- Add the missing versioning command to the semantic release step so the new version is calculated.
- Update to the newest Python actions for setup and checkout.
- Fix outdated syntax for referencing the version number in the `pyproject.toml` file to align with the requirements of the current version of Python Semantic Release.
- Update the `RELEASE_TOKEN` in the repository so Python Semantic Release can commit changes made during the release workflow.
=> ci: fix failing release workflow

docs/source/dev/maintaining.rst, docs/source/index.rst
Replaced incorrect convert branch reference with main to fix codecov workflow and documentation accuracy. Note, the documentation issue is only an unused reference.
=> docs: correct branch reference for codecov and documentation

src/soso/utilities.py, tests/test_utilities.py
Address an issue in the `is_url` function where bytes objects are being compared to string objects using the `==` operator, leading to unexpected results.
=> fix: incorrect comparison of bytes and string objects

src/soso/utilities.py, tests/test_utilities.py
Improve the `generate_citation_from_doi` utility function to reduce the likelihood of returning invalid citations when encountering invalid DOIs. This addresses a content negotiation issue where HTML content was inadvertently returned instead of the expected citation string.
Implement a heuristic approach using regular expression checks to identify basic HTML structures. This method offers a reliable way to detect invalid content without relying on full-fledged HTML parsers, which in preliminary testing erroneously flagged valid content and failed to identify invalid content.
Closes #221
=> fix: enhance `generate_citation_from_doi` for invalid input handling

src/soso/data/spase.xml
Remove the empty line at the beginning of the example SPASE file to ensure proper XML declaration and prevent parsing errors.
=> fix: correct XML declaration in example SPASE file (#213)

src/soso/main.py, tests/test_main.py
Modify the `main.convert` function to prevent the assignment of unrecognized properties to SOSO records when using the `kwargs` parameter. This ensures data integrity and prevents unexpected behavior.
Closes #218
=> fix: prevent invalid property assignments in SOSO records (#218)

tests/conftest.py, tests/test_main.py
Add the missing `@id` property to the `soso_properties` test fixture to prevent test failures caused by the absence of this required property.
This issue was discovered in #220.
=> test: add missing `@id` property to test fixture (#213)

.readthedocs.yml
Update `.readthedocs.yaml` to explicitly specify the path to `config.py`. This ensures proper documentation builds and avoids potential issues with an upcoming deprecation of inferred configuration.
=> build: configure Read the Docs for explicit path to config.py

README.md, docs/source/dev/contributing.rst, docs/source/index.rst
Improve the visibility of the project's Code of Conduct. Currently, the Code of Conduct is "buried" within the contributing guidelines, which can make it difficult for new and existing community members to find and understand the expected standards of behavior.
Closes #239
=> docs: improve the visibility of the Code of Conduct (#239)

poetry.lock, pyproject.toml
Remove the deprecated `[tool.poetry.dev-dependencies]` section from `pyproject.toml`, resolving deprecation warnings and streamlining the project configuration.
Closes #255
=> build: remove deprecated Poetry dev dependencies (#255)

.github/workflows/ci-cd.yml
Streamline the CI workflow by removing duplicate `poetry install` and Poetry setup steps before the `pylint` job. This improves CI efficiency and reduces overall build times.
Closes #257
=> ci: remove redundant Poetry and package installation (#257)

src/soso/utilities.py, tests/test_utilities.py
Change function return type hints and test assertions from the platform-specific pathlib.PosixPath to the abstract base class, pathlib.Path.
The use of PosixPath causes type hint issues and test failures on non-POSIX systems. Using the base class makes type hints and tests correct and portable across all operating systems.
Closes #261
=> fix: use platform-agnostic pathlib.Path type

problematicRecords.txt, src/soso/strategies/spase.py
Address linting and formatting issues that arose from the recent merge of the SPASE conversion strategy.
=> refactor: ensure SPASE strategy passes linting

docs/source/dev/design.rst
Document a design decision regarding the inclusion of shared infrastructure code within this project, even if it might technically fall slightly outside the project's primary scope of metadata conversion.
Closes #237
=> docs: accommodating shared infrastructure code (#237)

.github/CODEOWNERS, pyproject.toml
Add maintainers for relevant sections of the codebase to streamline pull request reviews and associated maintenance.
Closes #235
=> ci: add CODEOWNERS to streamline maintenance (#235)

src/soso/strategies/spase/spase.py
Register cleanup function with atexit to close the temp file on exit and to prevent unclosed file warnings during test runs and normal execution.
This was an oversight in review of PR #285
=> fix: ensure temporary SPASE file is properly closed

src/soso/strategies/spase/spase.py
Add a missing docstring to the temporary file cleanup function. It was forgotten in the original implementation.
=> docs: add missing docstring

.github/workflows/ci-cd.yml
Check the semantic-release command output to confirm a release was made before attempting to upload artifacts or publish to PyPI to avoid errors.
=> fix: conditionally run release steps in workflow

.zenodo.json
Address allowed value error in validation of .zenodo.json type field.
=> ci: fix .zenodo.json contributor types

src/soso/strategies/spase/spase.py
Contacts with an initial as first name or a
generational suffix (Jr., Sr., II, etc) split
and display properly
=> fix: address suffixes and first name initials

.github/workflows/ci-cd.yml
Check for a new release before attempting to upload to PyPI. This avoids workflow failure when no release is cut due to a lack of recent commits with release-triggering keywords.
=> ci: check for release before uploading to PyPI
