- src/soso/main.py
- tests/conftest.py
- tests/test_main.py
Add context to convert the JSON to JSON-LD and return the graph as a string so it can be written to file as text.
> fix: return JSON-LD str not JSON dict

- src/soso/data/soso-eml.sssom.tsv
- src/soso/main.py
- src/soso/strategies/eml.py
- tests/conftest.py
- tests/test_strategies.py
Get the SOSO "description" property from EML and add it to the returned graph.
> feat: get description property from EML (#5)

- src/soso/utilities.py
- tests/test_utilities.py
Create a utility function to generate a citation from a DOI for use in different strategy implementations.
> feat: generate citation from DOI

- docs/source/index.rst
Provide a basic usage example for converting a metadata record to SOSO format.
> docs: demonstrate basic usage

- docs/source/index.rst
Enumerate the prominent features of the application to provide users with an overview of its capabilities.
> docs: list features of this application

- docs/source/index.rst
Revise the top-level project description in the README to provide a clearer and more accurate overview of the project.
> docs: update project description in README

- docs/source/index.rst
Update the project description to better align with the mission statement of Science-On-Schema.Org, ensuring consistency and clarity.
> docs: align project description with SOSO

- docs/source/user/quickstart.rst
Update the title of the property addition demo to make clear that the section pertains to the addition of unmappable properties.
> docs: update title of property addition demo

- docs/source/user/quickstart.rst
Demonstrate the property overwrite process in its own section to delineate if from the related but different process of adding unmappable properties.
> docs: demo property overwrite

- docs/source/user/quickstart.rst
Demonstrate the process of overriding property methods to only slightly modify existing implementations. This can be useful when most of the return value should be preserved, but only a part of it changed.
> docs: demo property method override

- docs/source/user/quickstart.rst
Demonstrate the construction of a wrapper function utilizing metadata conversion, adding unmappable properties, and overwriting property methods.
> docs: demo wrapper function construction

- docs/source/user/quickstart.rst
Add a notes section to the quickstart guide for miscellaneous items.
> docs: add quickstart notes

- environment-min.yml
- environment.yml
- poetry.lock
- pyproject.toml
- requirements.txt
Remove pandas from package dependencies. It is no longer used as of commit: 01576226d0a6bdfbe9d0cbbfbd23fa140d28f7af.
> build: remove unused Pandas

- docs/source/dev/design.rst
Link the design notes on customization to the examples in the quickstart guide to provide additional details.
> docs: link to quickstart guide for customization

- docs/source/dev/contributing.rst
- docs/source/index.rst
- docs/source/user/support.rst
Emphasize the package name for consistent formatting.
> docs: consistently emphasize package name

- docs/source/user/quickstart.rst
Clean up a few minor items in the code of the "Wrapping it All Up" demo.
> docs: clean up code in "Wrapping it All Up" demo

- docs/source/dev/design.rst
Define what constitutes an acceptable mapping implementation to inform developer and maintainer decision-making.
> docs: define "acceptable mapping implementation"

- src/soso/utilities.py
- tests/test_utilities.py
Create a utility function to cast values to numeric types. This aids in the process of metadata conversion.
> feat: cast value to numeric type

- docs/source/dev/design.rst
- Enhance clarity and conciseness of core design requirements descriptions for better understanding.
- Remove testing strategy as it's a non-functional requirement.
> docs: improve design requirement clarity

- README.md
Added installation instructions and a quickstart example to the README for improved user experience.
> docs: enhance README with installation and quickstart

- .github/workflows/ci-cd.yml
Correct code coverage report generation in GitHub Actions workflow.
> ci: fix code coverage report generation

- README.md
- docs/source/index.rst
Replaced outdated codecov badge with the latest coverage data.
> docs: update codecov badge to reflect current coverage

- src/soso/utilities.py
- tests/test_utilities.py
Add a utility function to heuristically determine if a given string is a URL, enhancing validation and quality control capabilities. This function aims to differentiate URLs from unstructured text descriptions without guaranteeing absolute certainty.
> feat: implement heuristic URL validation utility

- src/soso/strategies/spase.py
> fix: translate docstrings into comments (#222)

- .pre-commit-config.yaml
Here is a PR for adding an example pre-commit config file (which works for well me). 
This should solve feature request #224
> feat: add precommit config file (#224)

- README.md
- docs/source/index.rst
Add the Zenodo DOI badge to the README and index.rst files for user reference.
Closes #241
> docs: add Zenodo DOI badge (#241)

- .github/workflows/ci-cd.yml
Revert to the previous PyPI release method temporarily due to issues with Trusted Publishing.
> ci: revert to previous PyPI release method
